#!/usr/bin/env python3
"""Generate the partial SystemVerilog decode table from the canonical ISA DB."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.isa.isa_db import IsaDatabase  # noqa: E402

OUTPUT = ROOT / "rtl/generated/tms34020_isa_decode.svh"


def identifier(mnemonic: str) -> str:
    return "TMS20_OP_" + "".join(
        character if character.isalnum() else "_"
        for character in mnemonic.upper()
    )


def case_pattern(mask: int, value: int) -> str:
    return "".join(
        str((value >> bit) & 1) if mask & (1 << bit) else "?"
        for bit in range(15, -1, -1)
    )


def render(database: IsaDatabase) -> str:
    instructions = sorted(
        database.instructions,
        key=lambda entry: (-entry.opcode_mask.bit_count(), entry.mnemonic),
    )
    enum_width = max(1, len(instructions).bit_length())
    lines = [
        "// Generated by tools/generators/generate_isa_rtl.py.",
        "// Source: docs/generated/tms34020_isa.yaml.",
        "// Coverage is intentionally partial; unmatched words are unclassified.",
        "`ifndef TMS34020_ISA_DECODE_SVH",
        "`define TMS34020_ISA_DECODE_SVH",
        "",
        f"typedef enum logic [{enum_width - 1}:0] {{",
        f"    TMS20_OP_UNCLASSIFIED = {enum_width}'d0,",
    ]
    for index, instruction in enumerate(instructions, start=1):
        comma = "," if index < len(instructions) else ""
        lines.append(
            f"    {identifier(instruction.mnemonic)} = "
            f"{enum_width}'d{index}{comma}"
        )
    lines.extend(
        [
            "} tms34020_opcode_id_t;",
            "",
            "typedef struct packed {",
            "    logic valid;",
            "    tms34020_opcode_id_t opcode_id;",
            "    logic [2:0] length_words;",
            "} tms34020_decode_t;",
            "",
            "function automatic tms34020_decode_t tms34020_decode_word(",
            "    input logic [15:0] first_word",
            ");",
            "    tms34020_decode_t decoded;",
            "    begin",
            "        decoded.valid = 1'b1;",
            "        decoded.opcode_id = TMS20_OP_UNCLASSIFIED;",
            "        decoded.length_words = 3'd0;",
            "        unique casez (first_word)",
        ]
    )
    for instruction in instructions:
        pattern = case_pattern(
            instruction.opcode_mask, instruction.opcode_value
        )
        lines.extend(
            [
                f"            16'b{pattern}: begin",
                f"                decoded.opcode_id = "
                f"{identifier(instruction.mnemonic)};",
                f"                decoded.length_words = "
                f"3'd{instruction.length_words};",
                "            end",
            ]
        )
    lines.extend(
        [
            "            default: begin",
            "                decoded.valid = 1'b0;",
            "                decoded.opcode_id = TMS20_OP_UNCLASSIFIED;",
            "                decoded.length_words = 3'd0;",
            "            end",
            "        endcase",
            "        return decoded;",
            "    end",
            "endfunction",
            "",
            "`endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in generated file differs",
    )
    args = parser.parse_args()
    expected = render(IsaDatabase.load())
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"FAIL: stale generated file: {OUTPUT}", file=sys.stderr)
            raise SystemExit(1)
        print("PASS: generated ISA RTL is current")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"WROTE: {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
